# Generated by Django 5.0.6 on 2025-02-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_address_customuser_cardnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='expire',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
