# Generated by Django 5.0.6 on 2025-02-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cardnumber',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cvc',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gsmnumber',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='zipcode',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
