# Generated by Django 5.0.6 on 2025-04-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_cardnumber_alter_customuser_cvc_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Kullanıcı', 'verbose_name_plural': 'Kullanıcılar'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cardnumber',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Kart Numarası'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Şehir'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ülke'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cvc',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Güvenlik Kodu'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Kullanıcı Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='expire',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Kart Son Kullanma tarihi'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='İsim'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gsmnumber',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefon Numarası'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Kullanıcı Aktiflik Durumu'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Kullanıcı Yönetici Paneline Giriş Yetkisi'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Kullanıcı Yönetici Yetkisi'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Soyisim'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='zipcode',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Posta Kodu'),
        ),
    ]
