# Generated by Django 5.0.6 on 2025-03-02 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Blog İsmi')),
                ('description', models.CharField(max_length=1000, verbose_name='Açıklama')),
                ('image', models.ImageField(upload_to='blogimages/', verbose_name='Blog Kapak Resmi')),
                ('content', models.TextField(verbose_name='Blog Yazısı')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
