# Generated by Django 5.0.6 on 2025-03-02 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blog_author_comment_blog_comments_commentreply_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
    ]
