# Generated by Django 5.0.6 on 2025-04-20 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_contact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Blog', 'verbose_name_plural': 'Bloglar'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Yorum', 'verbose_name_plural': 'Yorumlar'},
        ),
        migrations.AlterModelOptions(
            name='commentreply',
            options={'verbose_name': 'Yorum Yanıtı', 'verbose_name_plural': 'Yorum Yanıtları'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'İletişim Formu', 'verbose_name_plural': 'İletişim Formları'},
        ),
        migrations.AlterModelOptions(
            name='content',
            options={'verbose_name': 'İçerik', 'verbose_name_plural': 'İçerikler'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yazar'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, to='blogs.comment', verbose_name='Yorumlar'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='reply',
            field=models.ManyToManyField(blank=True, null=True, to='blogs.commentreply', verbose_name='Yorum Yanıtları'),
        ),
        migrations.AlterField(
            model_name='commentreply',
            name='content',
            field=models.TextField(verbose_name='Yorum Yanıt İçeriği'),
        ),
        migrations.AlterField(
            model_name='commentreply',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='content',
            name='content',
            field=models.TextField(verbose_name='İçerik'),
        ),
        migrations.AlterField(
            model_name='content',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Başlık(İsteğe Göre Yazılabilir)'),
        ),
    ]
