# Generated by Django 5.0.6 on 2025-02-15 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='İçecek İsmi')),
                ('image', models.ImageField(upload_to='coffeimages/', verbose_name='İçecek Resimleri')),
            ],
        ),
        migrations.CreateModel(
            name='Optionels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Opsiyon İsmi')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Opsiyon İsmi')),
                ('optionels', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.optionels', verbose_name='Opsiyon Kategorisi')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='İçecek İsmi')),
                ('description', models.TextField(verbose_name='İçecek Açıklaması')),
                ('price', models.FloatField(blank=True, verbose_name='Fiyat')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shop.images', verbose_name='İçecek Resimleri')),
                ('optionels', models.ManyToManyField(to='shop.optionels')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece', models.IntegerField(default=1)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.item')),
                ('options', models.ManyToManyField(blank=True, null=True, to='shop.option', verbose_name='Opsiyonlar')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('complete', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('orderitems', models.ManyToManyField(to='shop.orderitem')),
            ],
        ),
    ]
