# Generated by Django 5.0.6 on 2025-03-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='numberofsales',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
