# Generated by Django 5.0.6 on 2025-03-02 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_item_numberofsales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='numberofsales',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
