# Generated by Django 5.0.6 on 2025-03-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_item_numberofsales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='complete',
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
