# Generated by Django 5.0.6 on 2025-04-20 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_orderedcard'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'İçecek Resmi', 'verbose_name_plural': 'İçecek Resimleri'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'İçecek', 'verbose_name_plural': 'İçecekler'},
        ),
        migrations.AlterModelOptions(
            name='option',
            options={'verbose_name': 'Opsiyon', 'verbose_name_plural': 'Opsiyonlar'},
        ),
        migrations.AlterModelOptions(
            name='optionels',
            options={'verbose_name': 'Opsiyon Kategorisi', 'verbose_name_plural': 'Opsiyon Kategorileri'},
        ),
        migrations.AlterModelOptions(
            name='orderedcard',
            options={'verbose_name': 'Sipariş', 'verbose_name_plural': 'Siparişler'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Sipariş Edilen İçecek', 'verbose_name_plural': 'Sipariş Edilen İçecekler'},
        ),
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'verbose_name': 'Sepet', 'verbose_name_plural': 'Sepetler'},
        ),
        migrations.AlterField(
            model_name='item',
            name='numberofsales',
            field=models.IntegerField(blank=True, default=0, verbose_name='Satış Sayısı'),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='orderedcard',
            name='complete',
            field=models.BooleanField(default=False, verbose_name='Tamamlanma Durumu'),
        ),
        migrations.AlterField(
            model_name='orderedcard',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Sipariş Edilme Tarihi'),
        ),
        migrations.AlterField(
            model_name='orderedcard',
            name='shoppingcart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shoppingcart', verbose_name='Sepet'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.item', verbose_name='Sipariş Edilen İçecek'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='piece',
            field=models.IntegerField(default=1, verbose_name='İçecek Sayısı'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Müşteri'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Sepetin Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='ordered',
            field=models.BooleanField(default=False, verbose_name='Sipariş Edilme Durumu'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='orderitems',
            field=models.ManyToManyField(to='shop.orderitem', verbose_name='Sipariş Edilen İçecekler'),
        ),
    ]
